# Generated by Django 3.0 on 2020-05-27 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_product_catimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allcats', models.CharField(default='', max_length=50)),
                ('catimage', models.ImageField(default='', upload_to='shop/images')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='catimage',
        ),
    ]
